#%RAML 1.0 DataType
type: object
properties: 
  statusCode: string
  message: string
example:
  statusCode: 204 - No Content
  message: This method does not return a body in the response. Check the result of your action by sending a call to retrieve the response