#%RAML 1.0 SecurityScheme
type: x-customToken
description: This security scheme validates requests to the API using a token provided in the request header
describedBy: 
  headers: 
    Authorization:
      description: This header should contain a valid security token
      type: string